{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nhiid.fullname" . }}-secret
  labels:
    {{- include "nhiid.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-dsn: {{ include "nhiid.databaseDSN" . | quote }}
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.authTokens }}
  auth-tokens: {{ .Values.secrets.authTokens | quote }}
  {{- end }}
{{- end }}
